Home_Module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home_page'),
]

Main_Module/urls.py
from django.urls import path
from . import views
from .views import attendance_check, mark_complete, mark_complete2, mark_complete3, mark_complete4, mark_incomplete, \
    mark_incomplete2, mark_incomplete3, mark_incomplete4, message_parents

app_name = 'main'
urlpatterns = [
    path("home", views.index, name="home"),
    path("add/<str:pk>/", views.add_grade, name="add"),
    path("coursesview/<slug:slug>/<slug:slug2>/<slug:slug3>", views.courses_view, name='coursesview'),
    path("courses_date/<slug:slug>/<slug:slug2>/", views.courses_date, name='courses_date'),
    path("courses/<slug:slug>", views.courses, name='courses'),
    path("final_courses/<slug:slug>", views.final_courses, name='final_courses'),
    path("all_courses/<slug:slug>", views.all_courses, name='all_courses'),
    path("list", views.class_list, name="list"),
    path("reports/<slug:month>", views.report_card, name="reports"),
    path("final_reports/<slug:turn>", views.report_final, name="final_reports"),
    path("students/<slug:slug>/", views.ReportTemplateView.as_view(), name='students'),
    path("student_detail/<slug:slug>/<slug:month>", views.student_view, name="student_detail"),
    path("student_final/<slug:slug>/<slug:turn>", views.student_final, name="student_final"),
    path("checkbox", views.attendance, name="checkbox"),
    path("attendance/<slug:slug>/<slug:date>", attendance_check, name="attendance"),
    path('attendance/<slug:slug>/mark_complete/<int:todo_id>/', mark_complete, name="mark_complete"),
    path('attendance/<slug:slug>/mark_complete2/<int:todo_id>/', mark_complete2, name="mark_complete"),
    path('attendance/<slug:slug>/mark_complete3/<int:todo_id>/', mark_complete3, name="mark_complete"),
    path('attendance/<slug:slug>/mark_complete4/<int:todo_id>/', mark_complete4, name="mark_complete"),
    path('attendance/<slug:slug>/mark_incomplete/<int:todo_id>/', mark_incomplete, name="mark_incomplete"),
    path('attendance/<slug:slug>/mark_incomplete2/<int:todo_id>/', mark_incomplete2, name="mark_incomplete"),
    path('attendance/<slug:slug>/mark_incomplete3/<int:todo_id>/', mark_incomplete3, name="mark_incomplete"),
    path('attendance/<slug:slug>/mark_incomplete4/<int:todo_id>/', mark_incomplete4, name="mark_incomplete"),
    path('attendance/<slug:slug>/massage/<int:todo_id>/', message_parents, name="massage"),
    path('delete/<str:pk>', views.delete, name='delete'),
    path('update/<int:parent_id>/<slug:completion_date>', views.update_grades, name='update'),
    path('student_list/<slug:subject>/<int:classes>', views.student_list, name='student_list'),
    path('report/student_progress/<curse_name>/', views.student_progress_view, name='student_progress'),
    path('detail_progress/<slug:slug>/<curse_name>/', views.student_progress, name='detail_progress'),
    path('add_grade_a/<int:parent_id>/<slug:subject>', views.add_grade_a, name='add_grade_a'),
    path('add_grade_b/<int:parent_id>/<slug:subject>', views.add_grade_p, name='add_grade_b'),
    path('add_grade_c/<int:parent_id>/<slug:subject>', views.add_grade_c, name='add_grade_c'),
    path('finall_grade/<slug:parent_id>/<slug:subject>/<slug:turn>', views.final_grade, name='finall_grade'),
    path('class_finall_grade/<slug:parent_id>/<slug:subject>/<slug:turn>', views.class_final_grade,
         name='class_finall_grade'),
    path('summer_grade/<slug:parent_id>/<slug:subject>/', views.summer_grades, name='summer_grade'),
    path('yearly_final/<slug:slug>/', views.yearly_final, name='yearly_final'),
    path('allow/<str:parent_id>/', views.allow_promotion, name='allow'),
]

Sh_High_School/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Sh_High_School import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Authentication_Module.urls')),
    path('', include('Home_Module.urls')),
    path('', include('Contact_Module.urls')),
    path('', include('Profile_Module.urls')),
    path('', include('Main_Module.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main_Module/views.py
from datetime import timedelta
from statistics import mean
import jalali_date
from django.contrib import messages
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView
from .form import *
from .model import *
from .signals import *
from Authentication_Module.models import *
import math
from django.db import transaction

print('this is git commited')

# |--------------------------------------------------|#
# |-NOTE: STUDENT AND GRADES RELATED FORMS AND VIEWS-|#
# |--------------------------------------------------|#

abslout_date = jalali_date.date2jalali(datetime.date.today()).strftime('%Y-%m-%d')
date = jalali_date.date2jalali(datetime.date.today())
month_filter = date.month


def index(request):
    with transaction.atomic():  # Ensure the operation is atomic
        grades = Grades.objects.all()
        final_grades = FinalGrades.objects.all()
        students = StudentAccount.objects.all()

        for grade in final_grades:
            if grade.archived != True:
                grade.archived = True
                grade.save()

        for grade in grades:
            if grade.archived != True:
                grade.archived = True
                grade.save()

        for student in students:
            current_class = student.classes
            current_base = current_class.base

            # Ensure the current base is a number and can be incremented
            try:
                current_base_number = int(current_base.base_grade)
            except ValueError:
                print(f"Invalid base for class {current_class.class_name}: {current_base.base_grade}")
                continue

            # Calculate the next base number
            if current_base_number != 12 and student.allowed_to_promoted == True:
                next_base_number = current_base_number + 1
                print(current_base_number)

                # Check if the next base already exists, or create it
                next_base, created = Base.objects.get_or_create(base_grade=str(next_base_number))

                # Ensure no duplicate class records are created
                next_class_name = current_class.class_name
                next_class, _ = Classes.objects.get_or_create(class_name=next_class_name, base=next_base)

                # Update the student's class to the new class
                student.classes = next_class
                student.save()

                if created:
                    print(f"Created new base")

            elif current_base_number == 12 and student.status == False and student.allowed_to_promoted == True:
                student.graduate = True
                student.save()

            elif current_base_number == 12 and student.status == True:
                student.graduate = False
                student.save()

            elif current_base_number >= 12 and student.status == True:
                student.classes = student.classes

    context = {'classes': students}
    return render(request, "main/main.html", context)


# viewing lists of courses and subjects and editing them


def courses_view(request, slug, slug2, slug3):
    report = Grades.objects.filter(subject=slug, classes=slug2, date=slug3)

    context = {'report': report}
    return render(request, 'main/table.html', context)


@check_role_teacher
def courses_date(request, slug, slug2):
    report = Grades.objects.filter(subject=slug, classes=slug2)

    context = {'report': report}
    return render(request, 'main/course_date.html', context)


# list of courses every teacher has

@check_role_teacher
def courses(request, slug):
    report = ClCourses.objects.filter(student=request.user.id, slug=slug)
    report_a = ClCourses.objects.filter(student=request.user.id, slug=slug)
    a = 'A'
    b = 'B'
    c = 'C'
    classes = f'/attendance/{slug}/{abslout_date}'
    print(report)
    context = {'report': report, 'classes': classes, 'report_a': report_a, 'a': a, 'b': b, 'c': c, 'date': abslout_date}
    return render(request, 'main/courses.html', context)


def all_courses(request, slug):
    course = Course.objects.all()
    classes = Classes.objects.get(slug=slug)
    detail = BaseFields.objects.filter(id=request.user.id).first()
    class_id = classes.id
    context = {
        'course': course, 'slug': class_id, 'detail': detail,
    }
    return render(request, 'main/all_courses.html', context)


# function for each student to view thrier report card

def report_card(request, month):
    dates = datetime.date.today().month

    date = jalali_date.date2jalali(datetime.date.today()).month
    months = str(month)

    detail = StudentAccount.objects.get(id=request.user.id)
    student_a = Grades.objects.filter(student=request.user, time__icontains=f'-{months}-').order_by('date')

    detail.status = False
    detail.save()

    grades = Grades.objects.filter(student_id=detail.id, time__icontains=f'-{months}-').order_by('id')

    month_count = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    jalali_months = ['دی', 'بهمن', 'فروردین', 'اسفند', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان',
                     'آذر', 'دی']

    current_month = jalali_months[int(month)]

    group = Group.objects.get(name='staff')

    unique_dates_a = list(student_a.values_list('date', flat=True).distinct())

    grades_by_subject_a = {}
    averages_by_subject_a = {}
    grades_by_subject_b = {}

    for grade in student_a:
        subject = grade.subject

        if subject not in grades_by_subject_a:
            grades_by_subject_a[subject] = {date: None for date in unique_dates_a}
            grades_by_subject_b[subject] = {date: None for date in unique_dates_a}

        if grade.grade_type == 'A':

            if grade.grades_100 >= 1.0:
                grades_by_subject_a[subject][grade.date] = (f'{grade.grades_100 / 5} | {grade.grades_20 / 5}')
                grades_by_subject_b[subject][grade.date] = ((grade.grades_100 * (75 / 100)) / 5) + (
                        (grade.grades_20 * (25 / 100)) / 5)

            elif grade.grades_100 <= 1.0:
                grades_by_subject_a[subject][grade.date] = (f'{grade.grades_20}')
                grades_by_subject_b[subject][grade.date] = (grade.grades_20)

            elif grade.grades_20 <= 1.0:
                grades_by_subject_a[subject][grade.date] = (f'{grade.grades_100}')
                grades_by_subject_b[subject][grade.date] = (grade.grades_100)

        elif grade.grade_type == 'B':

            grades_by_subject_a[subject][grade.date] = (f'{(grade.grades_100 * 5) + (grade.grades_20)}')
            grades_by_subject_b[subject][grade.date] = (grade.grades_100 * 5) + (grade.grades_20)

        elif grade.grade_type == 'C':

            grades_by_subject_a[subject][grade.date] = grade.grades_20
            grades_by_subject_b[subject][grade.date] = grade.grades_20

    total_sum = 0
    total_count = 0
    for subject, grades_dict in grades_by_subject_b.items():

        all_grades = [grade for grade in grades_dict.values() if grade is not None]
        # Get all non-None grades
        for subject, grades_dict in grades_by_subject_b.items():

            all_grades = [grade for grade in grades_dict.values() if grade is not None]  # Filter None values
            if all_grades:
                average = mean(all_grades)
                rounded_average = get_up_to_nearest_25(average)  # Round to nearest 0.25
                threshold = 10 if subject.grade_type == 'C' else 14 or 12 if subject.grade_type == "B" else 14
                passed = rounded_average >= threshold
                averages_by_subject_a[subject] = {
                    'average': rounded_average,
                    'status': 'پاس شده' if passed else 'مردود',

                }

                Grades.objects.filter(subject=subject, student=request.user).update(passed=passed)

                if passed == False:
                    detail.status = True
                    detail.save()

                total_sum += rounded_average
                total_count += 1

    total_average = total_sum / total_count if total_count > 0 else 0
    print(f' avg : {total_average}')
    rounded_total_average = get_up_to_nearest_25(total_average)
    table_rows_a = []
    for subject, grades_dict in grades_by_subject_a.items():
        row = [subject]  # Start the row with the subject name
        for date in unique_dates_a:
            row.append(grades_dict.get(date))  # Add grade or None for each date
        try:
            row.append(averages_by_subject_a[subject]['average'])
            row.append(averages_by_subject_a[subject]['status'])

        except:
            row.append('-')

        table_rows_a.append(row)

    data = []

    for grade in grades:
        if grade.grades_20 != None and grade.grades_100 != None:
            data.append({
                'subject': grade.subject.subject,
                'date': grade.date.strftime('%Y-%m-%d'),
                'grades': get_up_to_nearest_25(((grade.grades_100 * (75 / 100)) / 5) + ((grade.grades_20 * (
                        25 / 100)) / 5)) if grade.subject.grade_type == 'A' else get_up_to_nearest_25(
                    grade.grades_20) and (grade.grades_100 * 5) + (
                                                                                     grade.grades_20) if grade.subject.grade_type == "B" else grade.grades_20,

            })
        if grade is float:
            print(((grade.grades_100 * 5) + (grade.grades_20)))
        else:
            print(0)
    context = {'student_a': student_a, 'group': group, 'rounded_total_average':rounded_total_average,
               'detail': detail, 'unique_dates_a': unique_dates_a,
               'current_month': current_month, 'month_count': month_count, 'table_rows': table_rows_a,

Main_Module/templates/main/courses.html
<!DOCTYPE html>
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>صفحه انتخالات درس معلم</title>

    <!-- Bootstrap Version 5 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css"
        integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">

    <!-- CSS Link -->
    <link rel="stylesheet" href="/static/css/profile.css">
</head>

<body class="gradient-custom">

    <main class="container ">
        <div class="main-body">

            <!-- Breadcrumb -->
            <nav aria-label="breadcrumb" class="main-breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0)"></a></li>
                    <li class="breadcrumb-item active" aria-current="page">User Profile</li>
                </ol>
            </nav>
            <!-- /Breadcrumb -->

            <div class="row gutters-sm">
                <div class="col-md-4 mb-3 mt-4">
                    <!-- Card Body (Card 1) -->
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="/static/images/avatar.png" alt="Admin" class="rounded-circle" width="150">
                                <div class="mt-3">
                                    <h4>Sharogh</h4><br>

                                    <a href='/profile'><button class="btn btn-primary">بازگشت به پروفایل</button></a>
                                    <a href='{{classes}}'> <button class="btn btn-outline-primary">حضور و غیاب</button></a>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /Card Body (Card 1) -->

                    <!-- /Card Body (Card 2) -->
                </div>

                <div class="col-md-8">
                    <!-- Card Body (Card 3) -->
                    <div class="card mb-3 mt-4 shadow">
                        <div class="card-body">
                            <div class="row">
                                <h6 class="mb-0 col-md-12 text-center">Class Book</h6>
                            </div>
                            <hr>
                            <div class="row">

                                {% for i in report_a %}


                                {% if i.course_type == a %}
                                <div class="col-md-4 mb-3"><a href={% url 'main:add_grade_a' i.slug.id i.subject %}>
                                    <button
                                        class="btn btn-outline-primary btn-round w-100 py-5 shadow">{{ i.subject }} {{i.slug}}</button></a>
                                </div>
                                {% endif %}

                                {% if i.course_type == b %}
                                <div class="col-md-4 mb-3"><a href={% url 'main:add_grade_b' i.slug.id i.subject %}>
                                    <button
                                        class="btn btn-outline-primary btn-round w-100 py-5 shadow">{{ i.subject }} {{i.slug}}</button></a>
                                </div>
                                {% endif %}

                                {% if i.course_type == c %}
                                <div class="col-md-4 mb-3"><a href={% url 'main:add_grade_c' i.slug.id i.subject %}>
                                    <button
                                        class="btn btn-outline-primary btn-round w-100 py-5 shadow">{{ i.subject }} {{i.slug}}</button></a>
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <!-- /Card Body (Card 3) -->
                </div>
            </div>
        </div>
    </main>
</body>

</html>

Main_Module/templates/main/delete.html
{%load static%}
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static '/css/main.css' %}">
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous" />
        <link rel="stylesheet" href="admin.css" />
        <title>Its</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="TemplateMo">
        
        <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    
        <title>Education Meeting HTML5 Template</title>
    
        <!-- Bootstrap core CSS -->
        <link href="static/assets/bootstrap.min.css" rel="stylesheet">
    
    
        <!-- Additional CSS Files -->
        <link rel="stylesheet" href="/static/assets/fontawesome.css">
        <link rel="stylesheet" href="/static/assets/templatemo-edu-meeting.css">
        <link rel="stylesheet" href="/static/assets/owl.css">
        <link rel="stylesheet" href="/static/assets/lightbox.css">
    </head>

<body background="iteampj/static/images/meetings-bg.jpg">

        <div class="upcoming-meetings">
    
        <div class="card card-body">
            <p> Are you sure you want to remove "{{item.grades}}" ?</p>
            <form method="POST" action="{% url 'main:delete' item.id %}">
                {% csrf_token %}
              
                <input class="btn btn-danger" type="submit" name="Remove" value="Remove">
                


            </form>
        </div>
    </div>
</div> 
</div>
</div>
<script src="/static/assets/jquery.min.js"></script>
    <script src="/static/assets/bootstrap.min.js"></script>

    <script src="/static/assets/isotope.min.js"></script>
    <script src="/static/assets/owl-carousel.js"></script>
    <script src="/static/assets/lightbox.js"></script>
    {% comment %} <script src="/static/assets/tabs.js"></script>
    <script src="/static/assets/video.js"></script>
    <script src="/static/assets/slick-slider.js"></script>
    <script src="/static/assets/custom.js"></script> {% endcomment %}
    <script>
        //according to loftblog tut
        $('.nav li:first').addClass('active');

        var showSection = function showSection(section, isAnimate) {
          var
          direction = section.replace(/#/, ''),
          reqSection = $('.section').filter('[data-section="' + direction + '"]'),
          reqSectionPos = reqSection.offset().top - 0;

          if (isAnimate) {
            $('body, html').animate({
              scrollTop: reqSectionPos },
            800);
          } else {
            $('body, html').scrollTop(reqSectionPos);
          }

        };

        var checkSection = function checkSection() {
          $('.section').each(function () {
            var
            $this = $(this),
            topEdge = $this.offset().top - 80,
            bottomEdge = topEdge + $this.height(),
            wScroll = $(window).scrollTop();
            if (topEdge < wScroll && bottomEdge > wScroll) {
              var
              currentId = $this.data('section'),
              reqLink = $('a').filter('[href*=\\#' + currentId + ']');
              reqLink.closest('li').addClass('active').
              siblings().removeClass('active');
            }
          });
        };

        $('.main-menu, .responsive-menu, .scroll-to-section').on('click', 'a', function (e) {
          e.preventDefault();
          showSection($(this).attr('href'), true);
        });

        $(window).scroll(function () {
          checkSection();
        });
    </script>
</body>

</html>
    </body>
</html>

Main_Module/templates/main/detail_progress.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>جدول و باکس اطلاعات</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body>
<br>
<h1 style="margin-right:7%;">مشاهده نمرات {{ report.date }}</h1>
<div class="container mt-5">
    <div class="card mb-4 bg-primary text-white text-center">
        <div class="row mt-3">
            <div class="col-md-3 fw-bold">
                <p><strong>نام: </strong> {{ detail.first_name }}</p>
            </div>
            <div class="col-md-3 fw-bold">
                <p><strong>نام خانوادگی: </strong>{{ detail.last_name }}</p>
            </div>
            <div class="col-md-3 fw-bold">
                <p><strong>نام پدر : </strong> {{ detail.father_name }}</p>
            </div>
            <div class="col-md-3 fw-bold">
                <p><strong>کلاس: </strong> {{ detail.classes }}</p>
            </div>
        </div>
    </div>
    <table class="table table-bordered shadow">
        <thead>
        <tr>
            <th>Subject</th>
            {% for date in unique_dates %}
                <th>{{ date }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for row in table_rows %}
            <tr>
                {% for cell in row %}
                    <td>{{ cell|default_if_none:"-" }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<h1>رشد تحصیلی {{ student.first_name }} {{ student.last_name }} در درس {{ report.first.subject }}</h1>

<canvas id="progressChart" width="800" height="400"></canvas>

<script>
    const gradesData = {{ grades|safe }};

    const labels = [];
    const dataPoints = [];

    gradesData.forEach(item => {
        labels.push(item.date);
        dataPoints.push(item.grades);
    });

    const ctx = document.getElementById('progressChart').getContext('2d');
    new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                label: 'روند نمرات',
                data: dataPoints,
                borderWidth: 2,
                tension: 0.4,
                segment: {
                    borderColor: (ctx) => {
                        const prev = ctx.p0.parsed.y;
                        const current = ctx.p1.parsed.y;
                        return current > prev ? 'green' : 'red';
                    }
                }
            }]
        },
        options: {
            responsive: true,
            plugins: {
                title: {
                    display: true,
                    text: 'نمودار رشد تحصیلی'
                }
            },
            scales: {
                y: {
                    beginAtZero: true,
                    title: {
                        display: true,
                        text: 'نمرات'
                    }
                },
                x: {
                    title: {
                        display: true,
                        text: 'تاریخ'
                    }
                }
            }
        }
    });
</script>

</body>

</html>

Main_Module/templates/main/final_courses.html
<!DOCTYPE html>
<html lang="fa">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>صفحه انتخالات درس معلم</title>

    <!-- Bootstrap Version 5 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css"
        integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">

    <!-- CSS Link -->
    <link rel="stylesheet" href="/static/css/profile.css">
</head>

<body class="gradient-custom">

    <main class="container ">
        <div class="main-body">

            <!-- Breadcrumb -->
            <nav aria-label="breadcrumb" class="main-breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="javascript:void(0)"></a></li>
                    <li class="breadcrumb-item active" aria-current="page">User Profile</li>
                </ol>
            </nav>
            <!-- /Breadcrumb -->

            <div class="row gutters-sm">
                <div class="col-md-4 mb-3 mt-4">
                    <!-- Card Body (Card 1) -->
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="/static/images/avatar.png" alt="Admin" class="rounded-circle" width="150">
                                <div class="mt-3">
                                    <h4>Sharogh</h4><br>

                                    <a href='/profile'><button class="btn btn-primary">بازگشت به پروفایل</button></a>
                                    <a href='{{classes}}'> <button class="btn btn-outline-primary">حضور و غیاب</button></a>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /Card Body (Card 1) -->

                    <!-- Card Body (Card 2) -->
                    <div class="">
                    </div>
                    <!-- /Card Body (Card 2) -->
                </div>

                <div class="col-md-8">
                    <!-- Card Body (Card 3) -->
                    <div class="card mb-3 mt-4 shadow">
                        <div class="card-body">
                            <div class="row">
                                <h6 class="mb-0 col-md-12 text-center">Class Book</h6>
                            </div>
                            <hr>
                            <div class="row">

                                {% for i in report_a %}


                                <div class="col-md-4 mb-3"><a href={% url 'main:finall_grade' i.slug.id i.subject 1 %}>
                                    <button
                                        class="btn btn-outline-primary btn-round w-100 py-5 shadow">{{ i.subject }} {{i.slug}}</button></a>
                                </div>
                               

                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <!-- /Card Body (Card 3) -->
                </div>
            </div>
        </div>
    </main>
</body>

</html>

Main_Module/templates/main/list.html
{% extends 'base.html' %}
{% block header %}
	<link rel="stylesheet" href="/static/css/table.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.2/css/bulma.min.css">
    <style>
        header {
            background-color: #6fa6f9e4;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container" style="margin-top: 120px; background-color: #cccccc; padding: 80px">
        <ul class="responsive-table">
            <li class="table-header">
                <div class="col col-4">نام</div>
                <div class="col col-3">درس</div>
                <div class="col col-4">کلاس</div>

            </li>
            {% for i in lists %}
                <li class="table-row">

                    <div class="col col-4" data-label="میانگین نمرات">{{ i }}</div>
                    <div class="col col-3" data-label=" لیست حضور و غیاب "><a href="{% url 'main:update' i.id date %}"
                                                                              style="text-decoration:none;"> لیست حضور و
                        غیاب </a></div>
                    <div class="col col-4" data-label="مشاهده نمرات"><a
                            href={% url 'main:students' i.id %} style="text-decoration:none;"> مشاهده نمرات</a></div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}